# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "pythom"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown
# Navigation
nav:
  - name:           "about"
    href:           "/about/"
  - name:           "github"
    href:           "//github.com/rubzk"
  - name:           "twitter"
    href:           "//twitter.com/rubiozk1"
  - name:           "linkedin"
    href:           "//linkedin.com/in/tomas-ertola/"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
